### ISSUE TITLE
Can't install any package of node-3d

### ISSUE THREAD

**Issue by leomelki** [node-3d/deps-opengl-raub#3]
When installing any of your packages, the installer is struggling to download some files. I manually downloaded some of these files but I can't find windows.zip for this repository. Is there any way to build it ourselves please ? Thank you a lot :)

**Comment by raub** [comment]
Hello. For this repository, the latest files are at https://github.com/node-3d/deps-opengl-raub/releases/tag/v3.0.0

What is your package manager? It is not NPM, is it?
See here: https://docs.npmjs.com/cli/v7/configuring-npm/package-json#config - there is this NPM feature allowing to add config variables, and it should work for NPM @6 @7

Well, anyway, I think this issue should be dealt with, in a way that works for everyone. I'll report back, when I come up with something

**Comment by raub** [comment]
Please, try glfw-raub@4.6.0 / deps-opengl-raub@4.0.0. Feel free to reopen with any new input, if the issue persists.
